# Generated by Django 3.2.12 on 2022-03-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20220329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='vendas.produto'),
        ),
    ]
